# Generated by Django 4.0.4 on 2023-04-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(choices=[('abdominals', 'Abdominals'), ('biceps', 'Biceps'), ('calves', 'Calves'), ('chest', 'Chest'), ('deltoids_front', 'Deltoids (Front)'), ('deltoids_middle', 'Deltoids (Middle)'), ('deltoids_rear', 'Deltoids (Rear)'), ('forearms', 'Forearms'), ('glutes', 'Glutes'), ('hamstrings', 'Hamstrings'), ('lats', 'Lats'), ('quadriceps', 'Quadriceps'), ('rhomboids', 'Rhomboids'), ('spinal_erectors', 'Spinal Erectors'), ('trapezius', 'Trapezius'), ('triceps', 'Triceps'), ('other', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('barbell', 'Barbell'), ('bands', 'Bands'), ('bodyweight', 'Bodyweight'), ('cable', 'Cable'), ('cardio', 'Cardio'), ('dumbbell', 'Dumbbell'), ('kettlebell', 'Kettlebell'), ('machine', 'Machine'), ('other', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight_system',
            field=models.CharField(choices=[('kg', 'kg'), ('lbs', 'lbs')], default='kg', max_length=6),
        ),
        migrations.AlterField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Finished', 'Finished')], default='Started', max_length=8),
        ),
    ]
