# Generated by Django 4.0.4 on 2023-05-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_exercise_reps_remove_exercise_sets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='api_id',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
