# Generated by Django 4.0.4 on 2023-05-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_exercise_api_id_alter_exercise_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='exercise',
            field=models.CharField(max_length=5),
        ),
    ]
